{% set name = "python-levenshtein" %}
{% set camelName = "python-Levenshtein" %}
{% set version = "0.12.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "033a11de5e3d19ea25c9302d11224e1a1898fe5abd23c61c7c360c25195e3eb1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - Levenshtein

about:
  home: http://github.com/ztane/python-Levenshtein
  license: GPL 2.0
  summary: 'Python extension for computing string edit distances and similarities.'
  description: |
    A Python extension written in C for fast computation of: Levenshtein (edit)
    distance and edit sequence manipulation; string similarity; approximate median
    strings, and generally string averaging; string sequence and set similarity.
    Levenshtein has a some overlap with difflib (SequenceMatcher). It supports
    only strings, not arbitrary sequence types, but on the other hand it's much
    faster.
  doc_url: https://rawgit.com/ztane/python-Levenshtein/master/docs/Levenshtein.html
  dev_url: http://github.com/ztane/python-Levenshtein

extra:
  recipe-maintainers:
    - pmlandwehr
