appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Wq/C+LiIcKjr3sxNqtxBtCL46qx5fGYHMxcoMVlDD18sonp1yGMlHOHYYiQ77JL8iHGufRFZp9qc8lnk8oxDA5/FJSFUNZ1c7NaeiYDEQkkKGGPNDsp9QLqiwJ7rqJYKQNgqwuXauMgwnpAGu/GR2lNypF3I48JeS6XNN6X6YAJJuuBBCjhYuf7rM+y/oM6I6mOuzhtwJxIhbKSooLuF2GTwNQGwdyRb6osWfe3+bSD6Voew5okDoOwR+O/flnAkq2r3jpmyAvqRX/lq2vJ8YHEPNnZqGE5t28KMBVqH5iKqee0ZLKFmjnisqIYGev1miagUHA6+9pXCYsaZCXuhCcqgpeFyQkGZDwpCf7MOBETbLh5i8yt7Ao4qbkoYD10ThN/B2r6hKPI3x5bnuiIXihEKWCV3ZRMUosguIo6bSAn2hngRpMKnmaCZAG4Hpro8eVixo4HLFlAs7Zzg9fcQq5GlSfSLZwmOAhEYmYBghpjU7RMLOnSOJet0yUAG5kizO/2Y5pPM8UaVXdKN8ugSxkP506e+7P2cWPJsV1vpXYi4HO5yhfeuQVkwwIGm2dqqTz4mEv29U4P/Fvxc89JW1SmOVst7V6W4lbLR//0ZgyIgXdnBiQQ96FFxaa6ZCjqpsWCzL5UOrWTsMzuv48QTLqY0inbyfwPX6CLgEvto44Q=}
provider:
  win: azure
conda_forge_output_validation: true
